import type { MemoryItem } from "./types";

export const memoryData: MemoryItem[] = [
  {
    id: "mem-001",
    memory: "User prefers Indonesian responses for product planning and UI discussions.",
    category: "Preference",
    scope: "Global",
    status: "active",
    source: "Chat preferences",
    lastUsed: "2026-05-14",
    updatedAt: "2026-05-13",
    confidence: 96,
  },
  {
    id: "mem-002",
    memory: "Langclaw dashboards should stay compact, scannable, and focused on operational work.",
    category: "Project",
    scope: "Langclaw Website",
    status: "active",
    source: "Workspace design notes",
    lastUsed: "2026-05-14",
    updatedAt: "2026-05-12",
    confidence: 91,
  },
  {
    id: "mem-003",
    memory: "API examples should mention secure key storage and avoid exposing keys in client-side code.",
    category: "API",
    scope: "API Playground",
    status: "active",
    source: "API key flow",
    lastUsed: "2026-05-12",
    updatedAt: "2026-05-10",
    confidence: 88,
  },
  {
    id: "mem-004",
    memory: "Project-specific chats can be pinned for recurring workstreams and benchmark notes.",
    category: "Workflow",
    scope: "Model Benchmark",
    status: "disabled",
    source: "Pinned projects",
    lastUsed: "2026-05-08",
    updatedAt: "2026-05-07",
    confidence: 74,
  },
  {
    id: "mem-005",
    memory: "User often asks for practical implementation details after a short design discussion.",
    category: "Personal",
    scope: "Global",
    status: "active",
    source: "Recent conversations",
    lastUsed: "2026-05-14",
    updatedAt: "2026-05-11",
    confidence: 84,
  },
  {
    id: "mem-006",
    memory: "Usage screens should expose balance, monthly consumption, and detailed transaction history.",
    category: "Project",
    scope: "Usage",
    status: "active",
    source: "Usage page",
    lastUsed: "2026-05-13",
    updatedAt: "2026-05-09",
    confidence: 82,
  },
  {
    id: "mem-007",
    memory: "RAG Knowledge Base work should prioritize source traceability and retrieval quality checks.",
    category: "Workflow",
    scope: "RAG Knowledge Base",
    status: "active",
    source: "Project chat",
    lastUsed: "2026-05-11",
    updatedAt: "2026-05-06",
    confidence: 79,
  },
  {
    id: "mem-008",
    memory: "Workspace settings are expected to include privacy controls for memory capture.",
    category: "Preference",
    scope: "Workspace Settings",
    status: "disabled",
    source: "Settings planning",
    lastUsed: "2026-05-06",
    updatedAt: "2026-05-05",
    confidence: 68,
  },
];
